// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CSharpSpecflow.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "pbi1235")]
    [Xunit.TraitAttribute("Category", "web")]
    public partial class SampleFeatureForWebApplications_MortgageCalculatorFeature : Xunit.IClassFixture<SampleFeatureForWebApplications_MortgageCalculatorFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "web - Copy.feature"
#line hidden
        
        public SampleFeatureForWebApplications_MortgageCalculatorFeature(SampleFeatureForWebApplications_MortgageCalculatorFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Sample Feature for web applications - Mortgage Calculator", "\tIn order to demonstrate the value of an open-source automation solution\r\n\tAs a Q" +
                    "A Automation Engineer\r\n\tI want to give an example of how to test using a feature" +
                    " file", ProgrammingLanguage.CSharp, new string[] {
                        "pbi1235",
                        "web"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Tooltip scenario")]
        [Xunit.TraitAttribute("FeatureTitle", "Sample Feature for web applications - Mortgage Calculator")]
        [Xunit.TraitAttribute("Description", "Tooltip scenario")]
        public virtual void TooltipScenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tooltip scenario", ((string[])(null)));
#line 8
 this.ScenarioSetup(scenarioInfo);
#line 9
  testRunner.Given("I am a user on Mortgage Calculator site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
  testRunner.When("I hover over \"icon next to Mortgage Amount\" by \"cssSelector\" with selector \"#mort" +
                    "ageCalculatorForm > ul.inputFieldList.clearfix.left > li:nth-child(1) > div > a\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
  testRunner.Then("I should see \"Mortgage Amount info popup\" with text \"Enter the amount of your new" +
                    " or existing mortgage here.\" by \"cssSelector\" with selector \"#mortageCalculatorF" +
                    "orm > ul.inputFieldList.clearfix.left > li:nth-child(1) > div > a > div\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Calculator scenario")]
        [Xunit.TraitAttribute("FeatureTitle", "Sample Feature for web applications - Mortgage Calculator")]
        [Xunit.TraitAttribute("Description", "Calculator scenario")]
        public virtual void CalculatorScenario()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculator scenario", ((string[])(null)));
#line 13
 this.ScenarioSetup(scenarioInfo);
#line 14
  testRunner.Given("I am a user on Mortgage Calculator site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
  testRunner.When("I enter text \"250000\" in the text field \"Mortgage Amount\" by \"id\" with selector \"" +
                    "amount\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
  testRunner.And("I enter text \"30\" in the text field \"Amortization Period\" by \"id\" with selector \"" +
                    "amortizationYears\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
  testRunner.And("I enter text \"30\" in the text field \"Interest Terms\" by \"id\" with selector \"inter" +
                    "estTermYears\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
  testRunner.And("I select option \"Fixed\" from dropdown \"Interest Type\" by \"id\" with selector \"inte" +
                    "restType\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
  testRunner.And("I enter text \"4.38\" in the text field \"Interest Rate\" by \"id\" with selector \"rate" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
  testRunner.And("I select option \"10\" from dropdown \"Start Date\" by \"id\" with selector \"startMonth" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
  testRunner.And("I select option \"2017\" from dropdown \"Start Date\" by \"id\" with selector \"startYea" +
                    "r\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
  testRunner.And("I select option \"Monthly\" from dropdown \"Payment period\" by \"id\" with selector \"p" +
                    "aymentMode\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
  testRunner.And("I click \"Calculate Now button\" by \"id\" with selector \"button\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
  testRunner.Then("I should see \"Payment Amount - 1st row\" with text \"$1,248.95\" by \"cssSelector\" wi" +
                    "th selector \"#mortgage > div.calcHolder.flexContainer.mortgage > div.mortageTabl" +
                    "eWrapper > table > tbody > tr.active > td:nth-child(2)\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 25
  testRunner.And("I should see \"Term Interest Cost - 1st row\" with text \"$199,622.19\" by \"cssSelect" +
                    "or\" with selector \"#mortgage > div.calcHolder.flexContainer.mortgage > div.morta" +
                    "geTableWrapper > table > tbody > tr.active > td:nth-child(4)\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SampleFeatureForWebApplications_MortgageCalculatorFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SampleFeatureForWebApplications_MortgageCalculatorFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
